name: CI


on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - 
        name: install jq
        id: install-jq
        run: sudo apt-get install jq
      - 
        name: Get musicbot version
        id: env
        run: |
          printf "MUSICBOT_VERSION=%s\n" "$(curl https://api.github.com/repos/jagrosh/MusicBot/releases/latest | jq .tag_name -r)" >> $GITHUB_ENV
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
                raiponce/musicbot:latest
                raiponce/musicbot:${{ env.MUSICBOT_VERSION }}
          build-args: |
            MVERSION=${{ env.MUSICBOT_VERSION }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
